title: "Flupp Wiki"
title_separator: "|"
repository: "koppor/wiki.flupp.de"
email: kopp.dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a information collected by Oliver Kopp
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wiki.flupp.de" # the base hostname & protocol for your site, e.g. http://example.com
locale: "en-US"
include: ["_pages"]

author:
  name: "Oliver Kopp"
  github: koppor
  twitter: *twitter

permalink: /:categories/:title/
breadcrumbs: true  # disabled by default
breadcrumb_home_label : "Home"
breadcrumb_separator  : ">"

markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

twitter:
  username: &twitter "koppor"

github:
  repository: "koppor/wiki.flupp.de"
  
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : "Oliver Kopp"
  links: # An array of links to social media profiles
    - "https://twitter.com/koppor"

search: true
search_full_content: true
